log_level: INFO

storage:
  # Storage path - where Qdrant will store collections and data
  storage_path: ${XDG_DATA_HOME}/claude/persistent_memory/qdrant

service:
  # HTTP API configuration
  host: 127.0.0.1
  http_port: 6333
  # gRPC API configuration
  grpc_port: 6334
  # Enable CORS for web interface access
  enable_cors: true

# Performance settings
cluster:
  # Disable clustering for single-node setup
  enabled: false

# Telemetry settings (disable for privacy)
telemetry_disabled: true